/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ubook;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.font.TextAttribute;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author AZHAR
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    CardLayout cardLayout;
    String jk;

    public Login() {
        initComponents();
        cardLayout = (CardLayout) (pnlLogin.getLayout());
        txtSignUp.setText("<HTML><U>Sign Up Now</U></HTML>");
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rgGender = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        pnlSideLogin = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnLoginSelect = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlLogin = new javax.swing.JPanel();
        pnlLoginCus = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtFieldUsernameCus = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtFieldPasswordCus = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnSignInCus = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtSignUp = new javax.swing.JLabel();
        pnlLoginEmp = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtLoginUsernameEmp = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtLoginPasswordEmp = new javax.swing.JPasswordField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnSignInEmp = new javax.swing.JButton();
        pnlSignUp = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        signUpNamaDepan = new javax.swing.JTextField();
        signUpPassword = new javax.swing.JPasswordField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        btnSignUp = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        signUpKTP = new javax.swing.JTextField();
        signUpEmail = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        signUpNoTelp = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        signUpNamaBelakang = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        signUpAlamat = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(284);
        jSplitPane1.setDividerSize(0);

        pnlSideLogin.setBackground(new java.awt.Color(246, 114, 128));
        pnlSideLogin.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(246, 114, 128));

        btnLoginSelect.setBackground(new java.awt.Color(53, 92, 125));
        btnLoginSelect.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnLoginSelect.setForeground(new java.awt.Color(255, 255, 255));
        btnLoginSelect.setText("Customer");
        btnLoginSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginSelectActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login as:");

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Copyright Azhar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLoginSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(106, 106, 106))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(345, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLoginSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pnlSideLogin.add(jPanel1, "card5");

        jSplitPane1.setLeftComponent(pnlSideLogin);

        pnlLogin.setBackground(new java.awt.Color(53, 92, 125));
        pnlLogin.setLayout(new java.awt.CardLayout());

        pnlLoginCus.setBackground(new java.awt.Color(53, 92, 125));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Customer Login");

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\BasisData\\icon\\outline_person_white_18dp.png")); // NOI18N

        txtFieldUsernameCus.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtFieldUsernameCus.setText("Masukkan Username / Email");
        txtFieldUsernameCus.setToolTipText("");
        txtFieldUsernameCus.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldUsernameCusFocusGained(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\BasisData\\icon\\outline_lock_white_18dp.png")); // NOI18N

        txtFieldPasswordCus.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtFieldPasswordCus.setText("jPasswordField1");
        txtFieldPasswordCus.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldPasswordCusFocusGained(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Password");

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Username");

        btnSignInCus.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnSignInCus.setText("Sign In");
        btnSignInCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInCusActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Dont Have Account ? ");

        txtSignUp.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        txtSignUp.setForeground(new java.awt.Color(255, 255, 255));
        txtSignUp.setText("Sign Up Now");
        txtSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSignUpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginCusLayout = new javax.swing.GroupLayout(pnlLoginCus);
        pnlLoginCus.setLayout(pnlLoginCusLayout);
        pnlLoginCusLayout.setHorizontalGroup(
            pnlLoginCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginCusLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(pnlLoginCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginCusLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlLoginCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(pnlLoginCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(pnlLoginCusLayout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSignUp))
                                .addComponent(txtFieldUsernameCus, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginCusLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlLoginCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(txtFieldPasswordCus, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSignInCus, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginCusLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(32, 32, 32)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        pnlLoginCusLayout.setVerticalGroup(
            pnlLoginCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginCusLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(pnlLoginCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtSignUp))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLoginCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFieldUsernameCus)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLoginCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFieldPasswordCus)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26)
                .addComponent(btnSignInCus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pnlLogin.add(pnlLoginCus, "card2");

        pnlLoginEmp.setBackground(new java.awt.Color(108, 91, 123));

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Employee Login");

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\BasisData\\icon\\outline_person_white_18dp.png")); // NOI18N

        txtLoginUsernameEmp.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtLoginUsernameEmp.setText("Masukkan Username / Email");
        txtLoginUsernameEmp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLoginUsernameEmpFocusGained(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\BasisData\\icon\\outline_lock_white_18dp.png")); // NOI18N

        txtLoginPasswordEmp.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtLoginPasswordEmp.setText("jPasswordField1");
        txtLoginPasswordEmp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLoginPasswordEmpFocusGained(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Password");

        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Username");

        btnSignInEmp.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnSignInEmp.setText("Sign In");
        btnSignInEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginEmpLayout = new javax.swing.GroupLayout(pnlLoginEmp);
        pnlLoginEmp.setLayout(pnlLoginEmpLayout);
        pnlLoginEmpLayout.setHorizontalGroup(
            pnlLoginEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginEmpLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(pnlLoginEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginEmpLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlLoginEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(txtLoginUsernameEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginEmpLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlLoginEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(txtLoginPasswordEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSignInEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginEmpLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(32, 32, 32)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        pnlLoginEmpLayout.setVerticalGroup(
            pnlLoginEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginEmpLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel17)
                .addGap(52, 52, 52)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLoginEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtLoginUsernameEmp)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLoginEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLoginPasswordEmp)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26)
                .addComponent(btnSignInEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pnlLogin.add(pnlLoginEmp, "card3");

        pnlSignUp.setBackground(new java.awt.Color(192, 108, 132));

        jLabel22.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Sign Up");

        signUpNamaDepan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        signUpPassword.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        jLabel25.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Password");

        jLabel26.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Nama Depan");

        btnSignUp.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("No. KTP");

        signUpKTP.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        signUpEmail.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        signUpEmail.setToolTipText("");

        jLabel28.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Email");

        signUpNoTelp.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        jLabel30.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("No. Telp");

        jLabel31.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Jenis Kelamin");

        rbLaki.setBackground(new java.awt.Color(192, 108, 132));
        rgGender.add(rbLaki);
        rbLaki.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rbLaki.setForeground(new java.awt.Color(255, 255, 255));
        rbLaki.setText("Laki - laki");
        rbLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLakiActionPerformed(evt);
            }
        });

        rbPerempuan.setBackground(new java.awt.Color(192, 108, 132));
        rgGender.add(rbPerempuan);
        rbPerempuan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rbPerempuan.setForeground(new java.awt.Color(255, 255, 255));
        rbPerempuan.setText("Perempuan");

        signUpNamaBelakang.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        jLabel32.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Nama Belakang");

        signUpAlamat.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        jLabel33.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Alamat");

        javax.swing.GroupLayout pnlSignUpLayout = new javax.swing.GroupLayout(pnlSignUp);
        pnlSignUp.setLayout(pnlSignUpLayout);
        pnlSignUpLayout.setHorizontalGroup(
            pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSignUpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(233, 233, 233))
            .addGroup(pnlSignUpLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSignUpLayout.createSequentialGroup()
                        .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlSignUpLayout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(signUpAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlSignUpLayout.createSequentialGroup()
                        .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlSignUpLayout.createSequentialGroup()
                                .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlSignUpLayout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(rbLaki)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbPerempuan))
                                    .addComponent(signUpNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSignUpLayout.createSequentialGroup()
                                .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSignUpLayout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addGap(18, 18, 18)
                                        .addComponent(signUpNamaBelakang, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSignUpLayout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(signUpNamaDepan, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlSignUpLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(signUpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(signUpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(signUpKTP, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(78, 78, 78))))
        );
        pnlSignUpLayout.setVerticalGroup(
            pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSignUpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(43, 43, 43)
                .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signUpNamaDepan, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel26))
                .addGap(10, 10, 10)
                .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signUpNamaBelakang, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signUpPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signUpKTP, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signUpEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signUpNoTelp, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signUpAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel33))
                .addGap(5, 5, 5)
                .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbLaki)
                    .addComponent(jLabel31)
                    .addComponent(rbPerempuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        pnlLogin.add(pnlSignUp, "card4");

        jSplitPane1.setRightComponent(pnlLogin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSignUpMouseClicked
        // TODO add your handling code here:
        btnLoginSelect.setBackground(new java.awt.Color(192, 108, 132));
        btnLoginSelect.setText("Back");
        pnlLogin.removeAll();
        pnlLogin.add(pnlSignUp);
        pnlLogin.repaint();
        pnlLogin.revalidate();
    }//GEN-LAST:event_txtSignUpMouseClicked

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=UBOOK;user=acer;password=123456";
            Connection con = DriverManager.getConnection(url);
            String query1 = "insert into CUSTOMER(NO_KTP, NAMA_DEPAN, NAMA_BELAKANG, EMAIL, JENIS_KELAMIN, PASSWORD, NO_TELP, NOREK_CUSTOMER, NO_KAMAR, ID_FAVORITE) "
                    + "values(?,?,?,?,?,?,?,null,null,null)";
            PreparedStatement pst = con.prepareStatement(query1);
            pst.setString(1, signUpKTP.getText());
            pst.setString(2, signUpNamaDepan.getText());
            pst.setString(3, signUpNamaBelakang.getText());
            pst.setString(4, signUpEmail.getText());
            if (rbLaki.isSelected()) {
                jk = "Laki - laki";
            }
            if (rbPerempuan.isSelected()) {
                jk = "Perempuan";
            }
            pst.setString(5, jk);
            pst.setString(6, signUpPassword.getText());
            pst.setString(7, signUpNoTelp.getText());
            pst.executeUpdate();

            String query2 = "insert into CUSTOMER_ALAMAT(ALAMAT,NO_KTP) values(?,?)";
            PreparedStatement pst2 = con.prepareStatement(query2);
            pst2.setString(1, signUpAlamat.getText());
            pst2.setString(2, signUpKTP.getText());
            pst2.executeUpdate();

            JOptionPane.showMessageDialog(null, "Berhasil Mendaftarkan");

//            Statement st = con.createStatement();
//            ResultSet rs = st.executeQuery(query1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void rbLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLakiActionPerformed

    private void txtFieldUsernameCusFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldUsernameCusFocusGained
        // TODO add your handling code here:
        if (txtFieldUsernameCus.getText().trim().equals("Masukkan Username / Email")) {
            txtFieldUsernameCus.setText("");
        }
    }//GEN-LAST:event_txtFieldUsernameCusFocusGained

    private void txtFieldPasswordCusFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldPasswordCusFocusGained
        // TODO add your handling code here:
        String myPass = String.valueOf(txtFieldPasswordCus.getPassword());
        if (myPass.equals("jPasswordField1")) {
            txtFieldPasswordCus.setText("");
        }
    }//GEN-LAST:event_txtFieldPasswordCusFocusGained

    private void txtLoginUsernameEmpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLoginUsernameEmpFocusGained
        // TODO add your handling code here:
        if (txtLoginUsernameEmp.getText().trim().equals("Masukkan Username / Email")) {
            txtLoginUsernameEmp.setText("");
        }
    }//GEN-LAST:event_txtLoginUsernameEmpFocusGained

    private void txtLoginPasswordEmpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLoginPasswordEmpFocusGained
        // TODO add your handling code here:
        String myPass = String.valueOf(txtLoginPasswordEmp.getPassword());
        if (myPass.equals("jPasswordField1")) {
            txtLoginPasswordEmp.setText("");
        }
    }//GEN-LAST:event_txtLoginPasswordEmpFocusGained

    private void btnLoginSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginSelectActionPerformed
        // TODO add your handling code here:
        if (btnLoginSelect.isSelected()) {
            btnLoginSelect.setBackground(new java.awt.Color(108, 91, 123));
            btnLoginSelect.setText("Employee");
            pnlLogin.removeAll();
            pnlLogin.add(pnlLoginEmp);
            pnlLogin.repaint();
            pnlLogin.revalidate();
        } else {
            btnLoginSelect.setBackground(new java.awt.Color(53, 92, 125));
            btnLoginSelect.setText("Customer");
            pnlLogin.removeAll();
            pnlLogin.add(pnlLoginCus);
            pnlLogin.repaint();
            pnlLogin.revalidate();
        }
    }//GEN-LAST:event_btnLoginSelectActionPerformed

    private void btnSignInCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInCusActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=UBOOK;user=acer;password=123456";
            Connection con = DriverManager.getConnection(url);
            String sql = "select * from Customer where email=? and password=?";
            PreparedStatement pst = con.prepareStatement(sql);
            String email = txtFieldUsernameCus.getText();
            pst.setString(1, txtFieldUsernameCus.getText());
            pst.setString(2, txtFieldPasswordCus.getText());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Username and Password Matched");
                String query2 = "Select NO_KTP from CUSTOMER where email=\'" + email + "\'";
                Statement st2 = con.createStatement();
                ResultSet r2 = st2.executeQuery(query2);
                String noKtp = rs.getString("NO_KTP");
                System.out.println(noKtp);
                MainCustomer mainCustomer = new MainCustomer(noKtp);
                mainCustomer.setVisible(true);
                setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Username and Password incorrect");
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_btnSignInCusActionPerformed

    private void btnSignInEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInEmpActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=UBOOK;user=acer;password=123456";
            Connection con = DriverManager.getConnection(url);
            String sql = "select * from Admin where ID_ADMIN=? and password=?";
            PreparedStatement pst = con.prepareStatement(sql);
            String id = txtLoginUsernameEmp.getText();
            pst.setString(1, id);
            pst.setString(2, txtLoginPasswordEmp.getText());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Username and Password Matched");
//                String query2 = "Select NO_KTP from CUSTOMER where email=\'" + email + "\'";
//                Statement st2 = con.createStatement();
//                ResultSet r2 = st2.executeQuery(query2);
//                String noKtp = rs.getString("NO_KTP");
//                System.out.println(noKtp);
                MainEmployee main = new MainEmployee(id);
                main.setVisible(true);
                setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Username and Password incorrect");
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnSignInEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnLoginSelect;
    private javax.swing.JButton btnSignInCus;
    private javax.swing.JButton btnSignInEmp;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlLoginCus;
    private javax.swing.JPanel pnlLoginEmp;
    private javax.swing.JPanel pnlSideLogin;
    private javax.swing.JPanel pnlSignUp;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.ButtonGroup rgGender;
    private javax.swing.JTextField signUpAlamat;
    private javax.swing.JTextField signUpEmail;
    private javax.swing.JTextField signUpKTP;
    private javax.swing.JTextField signUpNamaBelakang;
    private javax.swing.JTextField signUpNamaDepan;
    private javax.swing.JTextField signUpNoTelp;
    private javax.swing.JPasswordField signUpPassword;
    private javax.swing.JPasswordField txtFieldPasswordCus;
    private javax.swing.JTextField txtFieldUsernameCus;
    private javax.swing.JPasswordField txtLoginPasswordEmp;
    private javax.swing.JTextField txtLoginUsernameEmp;
    private javax.swing.JLabel txtSignUp;
    // End of variables declaration//GEN-END:variables
}
