/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ubook;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author AZHAR
 */
public class MainCustomer extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public MainCustomer() {
        initComponents();
        showUser();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    public ArrayList<Hotel> hotelList() {
        ArrayList<Hotel> hotelList = new ArrayList<>();

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=BasDat092;user=acer;password=123456";
            Connection con = DriverManager.getConnection(url);
            String query1 = "Select * from Hotel";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            Hotel hotel;
            while (rs.next()) {
//                hotel = new Hotel(rs.getString("idHotel"), rs.getString("nama"), rs.getFloat("harga"), rs.getString("alamat"),rs.getBytes("image"));
                hotel = new Hotel(rs.getString("idHotel"), rs.getString("nama"), rs.getString("alamat"), rs.getFloat("harga"), rs.getString("kuota"), rs.getBytes("gambar"), rs.getString("deskripsi"));
                hotelList.add(hotel);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return hotelList;
    }

    public void showUser() {
        ArrayList<Hotel> list = hotelList();
        DefaultTableModel model = (DefaultTableModel) HotelTable.getModel();
        Object[] row = new Object[5];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getNama();
            row[2] = list.get(i).getAlamat();
            row[3] = list.get(i).getHarga();
            row[4] = list.get(i).getKuota();
            try {

            } catch (Exception e) {
            }
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        pnlSideBarCus = new javax.swing.JPanel();
        sdbrHotel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sdbrFavorite = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sdbrChart = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sdbrProfil = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        pnlHotelBook = new javax.swing.JPanel();
        txtDisplayID = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtDisplayHarga = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        HotelTable = new javax.swing.JTable();
        btnBook = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDisplayDeskripsi = new javax.swing.JTextArea();
        txtDisplayAlamat = new javax.swing.JLabel();
        txtDisplayNama = new javax.swing.JLabel();
        imgHotel = new javax.swing.JLabel();
        btnFavorite = new javax.swing.JButton();
        pnlFavorite = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlCart = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        HotelTable2 = new javax.swing.JTable();
        btnBook1 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        pnlProfileCus = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(192, 108, 132));

        jSplitPane1.setDividerLocation(284);
        jSplitPane1.setDividerSize(1);

        pnlSideBarCus.setBackground(new java.awt.Color(53, 92, 125));

        sdbrHotel.setBackground(new java.awt.Color(192, 108, 132));
        sdbrHotel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sdbrHotel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sdbrHotelMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hotel");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\BasisData\\icon\\outline_apartment_white_18dp.png")); // NOI18N

        javax.swing.GroupLayout sdbrHotelLayout = new javax.swing.GroupLayout(sdbrHotel);
        sdbrHotel.setLayout(sdbrHotelLayout);
        sdbrHotelLayout.setHorizontalGroup(
            sdbrHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sdbrHotelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sdbrHotelLayout.setVerticalGroup(
            sdbrHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sdbrHotelLayout.createSequentialGroup()
                .addGroup(sdbrHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sdbrFavorite.setBackground(new java.awt.Color(108, 91, 123));
        sdbrFavorite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sdbrFavorite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sdbrFavoriteMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Favorite");

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\BasisData\\icon\\outline_favorite_border_white_18dp.png")); // NOI18N

        javax.swing.GroupLayout sdbrFavoriteLayout = new javax.swing.GroupLayout(sdbrFavorite);
        sdbrFavorite.setLayout(sdbrFavoriteLayout);
        sdbrFavoriteLayout.setHorizontalGroup(
            sdbrFavoriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sdbrFavoriteLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        sdbrFavoriteLayout.setVerticalGroup(
            sdbrFavoriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sdbrChart.setBackground(new java.awt.Color(108, 91, 123));
        sdbrChart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sdbrChart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sdbrChartMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cart");

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\BasisData\\icon\\outline_shopping_cart_white_18dp.png")); // NOI18N

        javax.swing.GroupLayout sdbrChartLayout = new javax.swing.GroupLayout(sdbrChart);
        sdbrChart.setLayout(sdbrChartLayout);
        sdbrChartLayout.setHorizontalGroup(
            sdbrChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sdbrChartLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        sdbrChartLayout.setVerticalGroup(
            sdbrChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        sdbrProfil.setBackground(new java.awt.Color(108, 91, 123));
        sdbrProfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sdbrProfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sdbrProfilMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Profile");

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\BasisData\\icon\\outline_person_white_18dp.png")); // NOI18N

        javax.swing.GroupLayout sdbrProfilLayout = new javax.swing.GroupLayout(sdbrProfil);
        sdbrProfil.setLayout(sdbrProfilLayout);
        sdbrProfilLayout.setHorizontalGroup(
            sdbrProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sdbrProfilLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        sdbrProfilLayout.setVerticalGroup(
            sdbrProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sdbrProfilLayout.createSequentialGroup()
                .addGroup(sdbrProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlSideBarCusLayout = new javax.swing.GroupLayout(pnlSideBarCus);
        pnlSideBarCus.setLayout(pnlSideBarCusLayout);
        pnlSideBarCusLayout.setHorizontalGroup(
            pnlSideBarCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sdbrChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sdbrFavorite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sdbrProfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sdbrHotel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlSideBarCusLayout.setVerticalGroup(
            pnlSideBarCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSideBarCusLayout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addComponent(sdbrHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sdbrFavorite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sdbrChart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sdbrProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        jSplitPane1.setLeftComponent(pnlSideBarCus);

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setLayout(new java.awt.CardLayout());

        txtDisplayID.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtDisplayID.setText("AB1234");
        txtDisplayID.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel13.setText("Alamat :");

        txtDisplayHarga.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtDisplayHarga.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtDisplayHarga.setText("Rp. 100.000");
        txtDisplayHarga.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jScrollPane1.setBackground(new java.awt.Color(192, 108, 132));
        jScrollPane1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        HotelTable.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        HotelTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Hotel", "Nama Hotel", "Alamat", "Harga", "Status Kuota"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        HotelTable.setGridColor(new java.awt.Color(192, 108, 132));
        HotelTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HotelTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(HotelTable);

        btnBook.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnBook.setText("Pesan");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        txtDisplayDeskripsi.setColumns(20);
        txtDisplayDeskripsi.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtDisplayDeskripsi.setRows(5);
        txtDisplayDeskripsi.setText("Deskripsi");
        jScrollPane2.setViewportView(txtDisplayDeskripsi);

        txtDisplayAlamat.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtDisplayAlamat.setText("Jalan Suhat");

        txtDisplayNama.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        txtDisplayNama.setText("Nama Hotel");

        imgHotel.setBackground(new java.awt.Color(0, 51, 51));
        imgHotel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgHotel.setText("NO IMAGE");
        imgHotel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnFavorite.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnFavorite.setText("Favorite");

        javax.swing.GroupLayout pnlHotelBookLayout = new javax.swing.GroupLayout(pnlHotelBook);
        pnlHotelBook.setLayout(pnlHotelBookLayout);
        pnlHotelBookLayout.setHorizontalGroup(
            pnlHotelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(pnlHotelBookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHotelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHotelBookLayout.createSequentialGroup()
                        .addGroup(pnlHotelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDisplayNama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlHotelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(pnlHotelBookLayout.createSequentialGroup()
                                .addComponent(txtDisplayID)
                                .addGap(191, 191, 191)
                                .addComponent(txtDisplayHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlHotelBookLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDisplayAlamat))))
                    .addGroup(pnlHotelBookLayout.createSequentialGroup()
                        .addComponent(btnFavorite, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlHotelBookLayout.setVerticalGroup(
            pnlHotelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHotelBookLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnlHotelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDisplayID)
                    .addComponent(txtDisplayHarga)
                    .addComponent(txtDisplayNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHotelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHotelBookLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlHotelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDisplayAlamat)
                            .addComponent(jLabel13)))
                    .addGroup(pnlHotelBookLayout.createSequentialGroup()
                        .addComponent(imgHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlHotelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFavorite, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pnlMain.add(pnlHotelBook, "card2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nama Hotel", "Image"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable1);

        javax.swing.GroupLayout pnlFavoriteLayout = new javax.swing.GroupLayout(pnlFavorite);
        pnlFavorite.setLayout(pnlFavoriteLayout);
        pnlFavoriteLayout.setHorizontalGroup(
            pnlFavoriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );
        pnlFavoriteLayout.setVerticalGroup(
            pnlFavoriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFavoriteLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 83, Short.MAX_VALUE))
        );

        pnlMain.add(pnlFavorite, "card3");

        jLabel21.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel21.setText("ID Pesanan             :");
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel22.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel22.setText("Alamat                     :");

        jScrollPane3.setBackground(new java.awt.Color(192, 108, 132));
        jScrollPane3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        HotelTable2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        HotelTable2.setForeground(new java.awt.Color(255, 255, 255));
        HotelTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pesanan", "Nama Hotel", "Alamat", "Harga", "Status Transaksi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        HotelTable2.setGridColor(new java.awt.Color(192, 108, 132));
        jScrollPane3.setViewportView(HotelTable2);

        btnBook1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnBook1.setText("Bayar");
        btnBook1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBook1ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel25.setText("Nama Hotel");

        jLabel26.setBackground(new java.awt.Color(0, 51, 51));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("NO IMAGE");
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel27.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel27.setText("Tanggal Check In    :");

        jLabel28.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel28.setText("Tanggal Check Out :");

        jLabel29.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel29.setText("Jenis Kamar            :");

        jLabel30.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel30.setText("Total Tagihan          :");

        javax.swing.GroupLayout pnlCartLayout = new javax.swing.GroupLayout(pnlCart);
        pnlCart.setLayout(pnlCartLayout);
        pnlCartLayout.setHorizontalGroup(
            pnlCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
            .addGroup(pnlCartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addGroup(pnlCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel29)
                    .addComponent(jLabel22)
                    .addComponent(jLabel30))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCartLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBook1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlCartLayout.setVerticalGroup(
            pnlCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCartLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCartLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30))
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(btnBook1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlMain.add(pnlCart, "card4");

        javax.swing.GroupLayout pnlProfileCusLayout = new javax.swing.GroupLayout(pnlProfileCus);
        pnlProfileCus.setLayout(pnlProfileCusLayout);
        pnlProfileCusLayout.setHorizontalGroup(
            pnlProfileCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );
        pnlProfileCusLayout.setVerticalGroup(
            pnlProfileCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );

        pnlMain.add(pnlProfileCus, "card5");

        jSplitPane1.setRightComponent(pnlMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sdbrHotelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sdbrHotelMouseClicked
        // TODO add your handling code here:
        sdbrHotel.setBackground(new java.awt.Color(192, 108, 132));
        sdbrFavorite.setBackground(new java.awt.Color(108, 91, 123));
        sdbrChart.setBackground(new java.awt.Color(108, 91, 123));
        sdbrProfil.setBackground(new java.awt.Color(108, 91, 123));

        pnlMain.removeAll();
        pnlMain.add(pnlHotelBook);
        pnlMain.repaint();
        pnlMain.revalidate();
    }//GEN-LAST:event_sdbrHotelMouseClicked

    private void sdbrFavoriteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sdbrFavoriteMouseClicked
        // TODO add your handling code here:
        sdbrHotel.setBackground(new java.awt.Color(108, 91, 123));
        sdbrFavorite.setBackground(new java.awt.Color(192, 108, 132));
        sdbrChart.setBackground(new java.awt.Color(108, 91, 123));
        sdbrProfil.setBackground(new java.awt.Color(108, 91, 123));

        pnlMain.removeAll();
        pnlMain.add(pnlFavorite);
        pnlMain.repaint();
        pnlMain.revalidate();
    }//GEN-LAST:event_sdbrFavoriteMouseClicked

    private void sdbrChartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sdbrChartMouseClicked
        // TODO add your handling code here:
        sdbrHotel.setBackground(new java.awt.Color(108, 91, 123));
        sdbrFavorite.setBackground(new java.awt.Color(108, 91, 123));
        sdbrChart.setBackground(new java.awt.Color(192, 108, 132));
        sdbrProfil.setBackground(new java.awt.Color(108, 91, 123));

        pnlMain.removeAll();
        pnlMain.add(pnlCart);
        pnlMain.repaint();
        pnlMain.revalidate();
    }//GEN-LAST:event_sdbrChartMouseClicked

    private void sdbrProfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sdbrProfilMouseClicked
        // TODO add your handling code here:
        sdbrHotel.setBackground(new java.awt.Color(108, 91, 123));
        sdbrFavorite.setBackground(new java.awt.Color(108, 91, 123));
        sdbrChart.setBackground(new java.awt.Color(108, 91, 123));
        sdbrProfil.setBackground(new java.awt.Color(192, 108, 132));

        pnlMain.removeAll();
        pnlMain.add(pnlProfileCus);
        pnlMain.repaint();
        pnlMain.revalidate();
    }//GEN-LAST:event_sdbrProfilMouseClicked

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
//        setVisible(false);
        DatePicker date = new DatePicker();
        date.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnBookActionPerformed

    private void btnBook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBook1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBook1ActionPerformed

    private void HotelTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HotelTableMouseClicked
        // TODO add your handling code here:
        int i = HotelTable.getSelectedRow();
        TableModel model=HotelTable.getModel();
        txtDisplayID.setText(model.getValueAt(i, 0).toString());
        txtDisplayNama.setText(model.getValueAt(i, 1).toString());
        txtDisplayAlamat.setText(model.getValueAt(i, 2).toString());
        txtDisplayHarga.setText("Rp. "+model.getValueAt(i, 3).toString());
        String desk=hotelList().get(i).getDeskripsi();
        txtDisplayDeskripsi.setText(desk);
//        byte[] img=(hotelList().get(i).getPicture());
//        ImageIcon imageIcon=new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(imgHotel.getWidth(), imgHotel.getHeight(), Image.SCALE_SMOOTH));
//        imgHotel.setIcon(imageIcon);

    }//GEN-LAST:event_HotelTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable HotelTable;
    private javax.swing.JTable HotelTable2;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnBook1;
    private javax.swing.JButton btnFavorite;
    private javax.swing.JLabel imgHotel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlCart;
    private javax.swing.JPanel pnlFavorite;
    private javax.swing.JPanel pnlHotelBook;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlProfileCus;
    private javax.swing.JPanel pnlSideBarCus;
    private javax.swing.JPanel sdbrChart;
    private javax.swing.JPanel sdbrFavorite;
    private javax.swing.JPanel sdbrHotel;
    private javax.swing.JPanel sdbrProfil;
    private javax.swing.JLabel txtDisplayAlamat;
    private javax.swing.JTextArea txtDisplayDeskripsi;
    private javax.swing.JLabel txtDisplayHarga;
    private javax.swing.JLabel txtDisplayID;
    private javax.swing.JLabel txtDisplayNama;
    // End of variables declaration//GEN-END:variables
}
